### ISSUE TITLE
Не запустилось с 'fbs run'

### ISSUE THREAD

**Issue by titov-vv** [flmnvd/3ndfl#1]
Может я конечно что-то не так понял или не так сделал, но при попытке запуска получил ошибку.
`(venv) [user@host 3ndfl]$ fbs run`
`Traceback (most recent call last):`
`  File "/home/user/3ndfl/venv/bin/fbs", line 33, in <module>
    sys.exit(load_entry_point('fbs==0.9.0', 'console_scripts', 'fbs')())  `
`  File "/home/user/3ndfl/venv/lib/python3.9/site-packages/fbs/__main__.py", line 17, in _main
    fbs.cmdline.main()  `
`  File "/home/user/3ndfl/venv/lib/python3.9/site-packages/fbs/cmdline.py", line 32, in main
    fn(*args)  `
`  File "/home/user/3ndfl/venv/lib/python3.9/site-packages/fbs/builtin_commands/__init__.py", line 96, in run
    subprocess.run([sys.executable, path(SETTINGS['main_module'])], env=env)  `
`KeyError: 'main_module'`  
`(venv) [user@host 3ndfl]$ `

**Comment by flmnvd** [comment]
Приветствую! Батники (fbs) для сборки бинарного дистрибутива. Запускаемый модуль здесь - main.py.
Но оно в любом случае пока мало юзабельно. Сейчас смотрю в сторону объединения с другими проектами.
https://github.com/titov-vv/jal/blob/master/docs/ru-tax-3ndfl/taxes.md
https://github.com/airens/interactive_brokers_tax
https://github.com/KonishchevDmitry/investments
https://github.com/cdump/investments
https://github.com/igor58279/ibtaxes
JAL и interactive_brokers_tax кажутся наиболее перспективными. Посмотрите, может быть для Ваших сделок этого функционала будет достаточно.

**Comment by titov-vv** [comment]
ok, я просто как раз думал что можно интересного для jal почерпнуть ;) хотел посмотреть

**Comment by flmnvd** [comment]
А. Прикольно. Вчера как раз пытался импортировать в JAL свой отчёт. Очень много не поддерживается. Например, у меня очень много Reverse Split, а так же операции в разных валютах вроде CAD и HKD. Мне кажется, я хорошо сделал запрос курсов. Так же они сериализуются и десериализуются. Курсы на выходные запрашиваются у ЦБ вместо самостоятельного расчёта. Запросы происходят автоматически без участия юзера (это как раз в JAL лишнее). Reverse Split как понимал я сделал и любые валюты поддерживаются.

**Comment by flmnvd** [comment]
Но работы ещё много. Сейчас вот думаю что проще - доделывать или присоединиться к кому-то ; )
